### ISSUE TITLE
Light theme/dark theme toggle

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/repodata#2]
A simple switch in the corner of the page. We have bootstrap so make sure to switch button classes.

**Comment by sejalmishra** [comment]
hey can i work on it?

**Comment by devkennyy** [comment]
Hey, of course!

**Comment by sejalmishra** [comment]
the "npm run install" did not work for me. Can you guide me on how to install dependencies and run runserver?

**Comment by devkennyy** [comment]
That's my mistake, it should be `npm install`

**Comment by sejalmishra** [comment]
yes that worked, but how to run the server, I followed the docs did not work for me.

**Comment by shamoon1997** [comment]
I am done with this task. Just making the pull request 
<img width="1433" alt="Screenshot 2022-08-06 at 12 56 25 PM" src="https://user-images.githubusercontent.com/49757455/183240202-236c12f3-1708-46f0-8a8d-9b174ef1290f.png">

**Comment by sejalmishra** [comment]
ohh okayy

**Comment by sejalmishra** [comment]
what command did you use to run the server

**Comment by devkennyy** [comment]
`http-server`
