### ISSUE TITLE
Add last updated field

### ISSUE THREAD

**Issue by devkennyy** [devkennyy/repodata#3]
The field results for `updated_at` aren't very legible to say the least (2018-06-23T23:02:07Z) We would have to convert this to a readable time.

**Comment by Ngoakor12** [comment]
What's do you mean by readable? using the above example(2018-06-23T23:02:07Z)

1. `23:02pm, 23 June 2018`? 
2. `23 June 2018, 23:02pm`?
3. `23 June 2018`?

**Comment by devkennyy** [comment]
The last one makes the most sense to me (3)

**Comment by Ngoakor12** [comment]
Cool, can I work on it?

**Comment by devkennyy** [comment]
Sorry for the late reply, you sure can!

**Comment by Ngoakor12** [comment]
Don't worry about it, I'll let you know if I encounter problems. I expect to open a pr latest Saturday, hopefully sooner.
